# vim: set ft=ansible
---
# Implement your Workload removal tasks here

- name: remove istio controlplane cr
  k8s:
    namespace: istio-system
    state: absent
    definition:
      apiVersion: maistra.io/v1
      kind: ServiceMeshControlPlane
      metadata:
        name: basic-install

- name: Ensure istio controlplane cr terminates before continuing
  k8s_facts:
    api_version: maistra.io/v1
    kind: ServiceMeshControlPlane
  register: result
  failed_when: result.resources | length > 0
  retries: 3
  until: result.resources | length == 0

- name: unapply servicemesh-operator.yaml
  block:
  - name: unapply servicemesh-operator.yaml
    k8s:
      state: absent
      definition: "{{ lookup('file','/tmp/istio-install/servicemesh-operator.yaml') }}"
  rescue:
  - name: create temp directory
    file:
      state: directory
      path: "/tmp/istio-install"
  - name: get servicemesh-operator.yaml
    get_url:
      force: yes
      url: "https://raw.githubusercontent.com/Maistra/istio-operator/maistra-0.11/deploy/servicemesh-operator.yaml"
      dest: "/tmp/istio-install/servicemesh-operator.yaml"
  - name: unapply servicemesh-operator.yaml
    k8s:
      state: absent
      definition: "{{ lookup('file','/tmp/istio-install/servicemesh-operator.yaml') }}"

- name: remove istio-system and istio-operator projects
  k8s:
    state: absent
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: "{{ item }}"
  with_items:
    - istio-system
    - istio-operator

- name: remove temp directory
  file:
    state: absent
    path: "/tmp/istio-install"

- name: Ensure project istio-system istio-operator is done terminating if it was being terminated
  k8s_facts:
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ item }}"
  with_items:
    - istio-system
    - istio-operator
  register: result
  failed_when: result.resources | length > 0
  retries: 60
  until: result.resources | length == 0

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
