# vim: set ft=ansible
---
# Implement your Workload deployment tasks here

# Target: OCP4.1, Tech Preview 11
# Source install instruction from https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html

- name: create temp directory
  file:
    state: directory
    path: "/tmp/istio-install"

- name: get servicemesh-operator.yaml
  get_url:
    force: yes
    url: "https://raw.githubusercontent.com/Maistra/istio-operator/maistra-0.11/deploy/servicemesh-operator.yaml"
    dest: "/tmp/istio-install/servicemesh-operator.yaml"

- name: create istio-system and istio-operator projects
  k8s:
    state: present
    definition:
      apiVersion: project.openshift.io/v1
      kind: Project
      metadata:
        name: "{{ item }}"
  with_items:
    - istio-system
    - istio-operator

- name: apply servicemesh-operator.yaml
  k8s:
    state: present
    definition: "{{ lookup('file','/tmp/istio-install/servicemesh-operator.yaml') }}"
  register: result
- debug: var=result

# from https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html
- name: istio controlplane cr
  k8s:
    namespace: istio-system
    state: present
    definition:
      apiVersion: maistra.io/v1
      kind: ServiceMeshControlPlane
      metadata:
        name: basic-install
      spec:
        threeScale:
          enabled: false
        istio:
          global:
            proxy:
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 128Mi
          gateways:
            istio-egressgateway:
              autoscaleEnabled: false
            istio-ingressgateway:
              autoscaleEnabled: false
              ior_enabled: false
          mixer:
            policy:
              autoscaleEnabled: false
            telemetry:
              autoscaleEnabled: false
              resources:
                requests:
                  cpu: 100m
                  memory: 1G
                limits:
                  cpu: 500m
                  memory: 4G
          pilot:
            autoscaleEnabled: false
            traceSampling: 100.0
          kiali:
            dashboard:
              user: admin
              passphrase: admin
          tracing:
            enabled: true
          multitenant: false


- name: wait up to 5 minutes for istio operator pod to be ready
  shell: "oc get deployment -n istio-operator istio-operator -o jsonpath='{.status.readyReplicas}'"
  register: istio_deployment_status
  until: "istio_deployment_status.stdout | int >= 1"
  retries: 5
  delay: 60

- name: wait up to 8 minutes for the elasticsearch statefulset to exist
  shell: "oc get statefulset elasticsearch -n istio-system"
  register: elasticsearch_set_status
  until: elasticsearch_set_status.rc == 0
  retries: 8
  delay: 60

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool

