---
# workload vars
oadp_operator_release: "v0.3.0"
oadp_subscription_wait: 20

oadp_state: "present"
oadp_namespace: "openshift-adp"
oadp_download_content:
- url: "https://raw.githubusercontent.com/konveyor/mig-agnosticd/master/files/prepare_station.sh"
  target_dir: ""
- url: "https://raw.githubusercontent.com/konveyor/mig-agnosticd/master/files/bookbag.yml"
  target_dir: ""
- url: "https://raw.githubusercontent.com/konveyor/mig-agnosticd/master/files/lab8/probe.sh"
  target_dir: ""
- url: "https://raw.githubusercontent.com/konveyor/mtc-breakfix/master/01-Misconfiguration/01-misconfig.yml"
  target_dir: "/files/debug/ex1/"
- url: "https://raw.githubusercontent.com/konveyor/mtc-breakfix/master/03-Gvk/03-dest-manifest.yml"
  target_dir: "/files/debug/ex3/"

oadp_workload_destroy: "{{ false if (ACTION=='create' or ACTION=='provision') else true }}"
oadp_workload_title: "{{ 'Creating' if not oadp_workload_destroy else 'Removing' }}"
oadp_workload_state: "{{ 'present' if not oadp_workload_destroy else 'absent' }}"     # state of k8s resources
silent: false
noobaa_s3_endpoint_proto: https
ocs_migstorage: false
ocs_migstorage_bucketname: migstorage
ocs_migstorage_namespace: openshift-migration
# undefined variables
# oadp_operator_ui_cluster_api_endpoint:

# Default to deploying bookbag with shell
ocp4_workload_oadp_deploy_bookbag: true

ocp4_workload_oadp_cluster_admin: >-
  {{ ocp4_workload_authentication_admin_user | default('admin') }}
ocp4_workload_oadp_cluster_admins: >-
  {{ ocp4_workload_authentication_admin_users
   | default([ocp4_workload_oadp_cluster_admin] if ocp4_workload_oadp_cluster_admin != '' else [])
  }}
