---
# workload vars
oadp_operator_release: "v0.3.0"
oadp_subscription_wait: 20

oadp_state: "present"
oadp_namespace: "openshift-adp"
oadp_download_content:
  - url: "https://raw.githubusercontent.com/konveyor/mig-agnosticd/master/files/prepare_station.sh"
    target_dir: ""
  - url: "https://raw.githubusercontent.com/konveyor/mig-agnosticd/master/files/bookbag.yml"
    target_dir: ""
  - url: "https://raw.githubusercontent.com/konveyor/mig-agnosticd/master/files/lab8/probe.sh"
    target_dir: ""
  - url: "https://raw.githubusercontent.com/konveyor/mtc-breakfix/master/01-Misconfiguration/01-misconfig.yml"
    target_dir: "/files/debug/ex1/"
  - url: "https://raw.githubusercontent.com/konveyor/mtc-breakfix/master/03-Gvk/03-dest-manifest.yml"
    target_dir: "/files/debug/ex3/"
aws_region: us-east-1
oadp_workload_destroy: "{{ false if (ACTION=='create' or ACTION=='provision') else true }}"
oadp_workload_title: "{{ 'Creating' if not oadp_workload_destroy else 'Removing' }}"
oadp_workload_state: "{{ 'present' if not oadp_workload_destroy else 'absent' }}"     # state of k8s resources
silent: false
noobaa_s3_endpoint_proto: http
ocs_migstorage: false
ocs_bucketname: migstorage
ocs_mcg_pv_pool_bucket_name: mcg
ocs_namespace: openshift-storage
# undefined variables
# oadp_operator_ui_cluster_api_endpoint:

# Default to deploying bookbag with shell
ocp4_workload_oadp_deploy_bookbag: true

ocp4_workload_oadp_cluster_admin: >-
  {{ ocp4_workload_authentication_admin_user | default('admin') }}
ocp4_workload_oadp_cluster_admins: >-
  {{ ocp4_workload_authentication_admin_users
   | default([ocp4_workload_oadp_cluster_admin] if ocp4_workload_oadp_cluster_admin != '' else [])
  }}

oadp_expected_crds:
  - veleroes.oadp.openshift.io
  - backups.velero.io
  - backupstoragelocations.velero.io
  - deletebackuprequests.velero.io
  - downloadrequests.velero.io
  - podvolumebackups.velero.io
  - podvolumerestores.velero.io
  - resticrepositories.velero.io
  - restores.velero.io
  - schedules.velero.io
  - serverstatusrequests.velero.io
  - volumesnapshotlocations.velero.io
